### ISSUE TITLE
Entity Loss/Duplicate UUID Issues

### ISSUE THREAD

**Issue by aikar** [PaperMC/Paper#1223]
UPDATE: Most issues around duplicate entities, the source of them and dealing with them in chunks should now be resolved. A new config option "duplicate-uuid-resolver" is now in your config on how to handle them.

Build 1526 adds a new (and now default) mode called "Safe regen" for handling duplicates. This mode will delete any entity of same type that is near each other. This should help alleviate any risk of vanilla bugs that caused duplicate entities from surfacing them.

Please go edit your configs and set:
`duplicate-uuid-resolver: saferegen`
in your default world config

If you've used a recent build, you already have this in your config and need to update.
If your updated from some older build pre 1500~ range to 1525+, then you will be on the new default

If you don't want to take any risk deleting an entity, then leave it on `regen`.
If you don't want to take any risk of having a duplicate entity and would rather delete any potentials, then change it to `delete`.
If you don't want to do anything to them and leave them in limbo state, change it to `warn` or `nothing`

In Limbo State, only 1 of the entities can be loaded into your world at a time. You may alternate which one ends up visible in the world due to Chunk Load Order, and will cause confusing situations. It is recommended you either use a regen strategy (so both live), or deletion to stop further log messages.

------------------------
While #1199 chased a lot of issues and did identify legit bugs in the recent performance work of avoiding chunk lookups, it can not be that patch as the issue occurred on my server before that patch was ever even made. That patch is also near equiv to Sponges version now.

~~Suspect 1: (Pretty confident is not it)~~
~~https://github.com/PaperMC/Paper/commit/ca0ec24d6482115e75a547115a75ed0ef4bae724~~
Analysis: This patch deals with Entity Removal, so I would suspect we would be having potential with duplicates rather than loss. Can not see how this can be source as the only thing that can set the flag to false is the called method.

~~Suspect 2:~~ ~~https://github.com/PaperMC/Paper/commit/e74e4584d6d1bd10a4d6929a0f1d90fb66fc0f69~~
~~Evidence against though is reports of no issues on 1468...~~

guaranteed issue found:
Squids were causing the Random Seed to be corrupted, creating predictable and reused UUID's. But suspect that this wasn't the ONLY issue. ongoing research.

Interestingly, this also is likely the source of the issue for #1219 and what is being reported in #1208

**Comment by aikar** [comment]
Ok I do not believe it is that commit in question. 
This patch would impact removal, but were having issues in reverse direction.

**Comment by Drc-DEV** [comment]
(Using build 1500) While it seemed that the bug was fixed, after a restart some of the NPCs disappeared again. I noticed that it happens often after restarts and after purging chunks. So maybe it's related to something acting on chunk load.

**Comment by LogGits** [comment]
@DracarysPro this is related to #1208 I also noticed whilst testing that this happens often when the server has just restarted or the chunks haven't been loaded yet.

**Comment by electronicboy** [comment]
I had a few theories last night, one of them ranging to “is it possible that we’re saving multiple entities into chunks and trying to load them back, causing somewhat undefined behavior”, no idea if that’s possible or what side effects we’d see from that;
I really need to find a way to replicate this locally, if somebody has a reasonably sized world save that they can provide that can replicate this, that might be handy, failing that I’ll try and get something setup to look into this when I have the time

On July 18, 2018 at 3:45:48 PM, Dracarys (notifications@github.com) wrote:

(Using build 1500) While it seemed that the bug was fixed, after a restart some of the NPCs disappeared again. I noticed that it happens often after restarts and after purging chunks. So maybe it's related to something acting on chunk load.

**Comment by aikar** [comment]
Copying @LogGits message from other ticket here:

@aikar 
**This was using Paper 1500:**
https://www.youtube.com/watch?v=RuQYaCzm-l4

Forgot to /ver but if its needed, ill redo it the experiment. **Wasn't able to test with no plugins at the time but i will tomorrow morning 👍 **

Same setup on 1468 works totally fine with no issues.

**EDIT: Forgot to mention that this often happens after restarts**

Steps to reproduce:
**EDIT: 1. Restart server.**
2. Warp into a random chunk far away from other players so you don't make their mobs vanish.
3. Place the mobs (doesnt affect wolves for some reason)
4. fly away and roam around for abit.
5. come back to reveal missing mobs.

If step 4 didnt work. Restart the server and repeat step 2.

My paper.yml config:
```yaml
# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our IRC channel.
# 
# IRC: #paper @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=paper )
# Wiki: https://paper.readthedocs.org/ 
# Paper Forums: https://aquifermc.org/ 

verbose: false
config-version: 13
settings:
  load-permissions-yml-before-plugins: true
  bungee-online-mode: true
  sleep-between-chunk-saves: false
  region-file-cache-size: 256
  save-empty-scoreboard-teams: false
  incoming-packet-spam-threshold: 300
  remove-invalid-statistics: true
  save-player-data: true
  use-alternative-luck-formula: false
  min-chunk-load-threads: 3
  suggest-player-names-when-null-tab-completions: true
  enable-player-collisions: true
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
messages:
  kick:
    authentication-servers-down: Mojang Authentication Servers are down.
    flying-player: Flying is not enabled on our server
    flying-vehicle: Flying is not enabled on our server
timings:
  enabled: true
  verbose: true
  server-name-privacy: true
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
world-settings:
  default:
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      flat-bedrock: false
      disable-extreme-hills-emeralds: false
      disable-extreme-hills-monster-eggs: false
      disable-mesa-additional-gold: false
    use-vanilla-world-scoreboard-name-coloring: false
    remove-corrupt-tile-entities: true
    use-chunk-inhabited-timer: true
    queue-light-updates: false
    portal-search-radius: 128
    delay-chunk-unloads-by: 10s
    max-auto-save-chunks-per-tick: 24
    save-queue-limit-for-auto-save: 50
    max-chunk-sends-per-tick: 81
    max-chunk-gens-per-tick: 10
    game-mechanics:
      allow-permanent-chunk-loaders: false
      scan-for-legacy-ender-dragon: true
      disable-end-credits: false
      disable-player-crits: false
      disable-sprint-interruption-on-attack: false
      shield-blocking-delay: 5
      disable-chest-cat-detection: true
      disable-unloaded-chunk-enderpearl-exploit: true
    max-growth-height:
      cactus: 3
      reeds: 3
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    despawn-ranges:
      soft: 32
      hard: 128
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    water-over-lava-flow-speed: 5
    fast-drain:
      lava: false
      water: false
    optimize-explosions: true
    lava-flow-speed:
      normal: 30
      nether: 10
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    filter-nbt-data-from-spawn-eggs-and-related: true
    max-entity-collisions: 8
    disable-creeper-lingering-effect: false
    hopper:
      cooldown-when-full: true
      disable-move-event: false
      push-based: false
    keep-spawn-loaded-range: 10
    auto-save-interval: -1
    nether-ceiling-void-damage: false
    allow-non-player-entities-on-scoreboards: false
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    container-update-tick-rate: 1
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    elytra-hit-wall-damage: true
    grass-spread-tick-rate: 1
    use-alternate-fallingblock-onGround-detection: false
    bed-search-radius: 1
    non-player-arrow-despawn-rate: 120
    prevent-tnt-from-moving-in-water: false
    keep-spawn-loaded: true
    anti-xray:
      enabled: true
      engine-mode: 2
      chunk-edge-mode: 1
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - planks
    experience-merge-max-value: -1
    armor-stands-do-collision-entity-lookups: true
    disable-thunder: false
    skeleton-horse-thunder-spawn-chance: 0.01
    disable-ice-and-snow: false
    fire-physics-event-for-redstone: false
    skip-entity-ticking-in-chunks-scheduled-for-unload: false
    spawner-nerfed-mobs-should-jump: false
    baby-zombie-movement-speed: 0.5
    allow-leashing-undead-horse: false
    mob-spawner-tick-rate: 1
    all-chunks-are-slime-chunks: false
    squid-spawn-height:
      maximum: 63.0
      minimum: 45.0
    disable-teleportation-suffocation-check: false
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
```
Same thing happens when using:
```
skip-entity-ticking-in-chunks-scheduled-for-unload: true
```
