### ISSUE TITLE
Anti-Xray doesn't update as you travel

### ISSUE THREAD

**Issue by tsiedsma** [PaperMC/Paper#1444]
### What behaviour is expected:
Teleported to a new random location in the world, go into spectator mode with an x-ray resource pack.
All ores are hidden as expected except for those exposed in caves.  Travel a couple of chunks away and ores start to become visible.  No amount of waiting results in the ores hiding.

If I teleport away and back, when that chunk reloads the ores are hidden.  Travel again and the same exposure of ores happens.

Would expect ores to hide as the new chunks are rendered in.

### Plugin list:
Grief Prevention
EssentialsX
the list goes on, but none that impact the rendering of ores.

### Paper build number:
Paper version git-Paper-253 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Anything else:
```
    anti-xray:
      enabled: true
      engine-mode: 1
      chunk-edge-mode: 1
      max-chunk-section-index: 2
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - planks
```

**Comment by aikar** [comment]
@stonar96

**Comment by stonar96** [comment]
Thanks for reporting it. I will take a look at it today. It's probably an easy fix. I might forgot to init DataPaletteBlock with predefined blocks somewhere.

Do you use a custom chunk generator or the default (inbuilt, vanilla) one?

**Comment by tsiedsma** [comment]
Thanks, just using the vanilla generator.

**Comment by stonar96** [comment]
I have now tried to reproduce this in the way you explained it. However I can't reproduce it neither with a 1.13 server (from my original Anti-Xray development branch) nor with the latest 1.13.1 version (from Papers master branch).

My guess is that you either see ores from chunk edges which are possible not obfuscated with `chunk-edge-mode: 1` or you see ores above your `max-chunk-section-index: 2` setting. Please try again with `chunk-edge-mode: 2` or `chunk-edge-mode: 3`

**Comment by tsiedsma** [comment]
If I'm looking around, I can't see any ores.  If I travel a few chunks I start to see them in the distance.
As I approach those chunks, the ores are very clearly visible.  If I relog or tp away and back, the ores are hidden until I travel again.  This is using a simple xray resource pack for 1.13.1 and in spectator mode.

I'm not sure how else to explain this.  I tried it with chunk-edge-mode: 2 and max-chunk-section-index: 2 and 3

**Comment by stonar96** [comment]
This is exactly what I did. I will wait until other people can confirm this bug. Just asked for it in the IRC. Sorry, there is nothing I can do as long as I can't reproduce it.

Edit: Note that you also have to restart your server if you change any settings. Reloading wont work. Can you try it on a test server without any other settings or plugins?

**Comment by tsiedsma** [comment]
Totally understand.  I'd make a video but that still won't help you.  And yeah I can try it on a test server to see.

**Comment by egg82** [comment]
A video showing the bug in greater detail. At least I THINK this is the same bug. It seems extremely similar. Latest paper compiled/patched with `./paper test` and anti-xray values set to the same as first posted.

https://www.youtube.com/watch?v=xAgzXjV5Gig

**Comment by egg82** [comment]
The important note is that it seems to only affect ores over a certain height. Anything in the deeper levels is still hidden.

**Comment by tsiedsma** [comment]
Yeah, that's not quite what I was seeing so I'll see what I can do to better show my experience.

**Comment by stonar96** [comment]
@aikar The video doesn't show an issue. ~~This still needs testing.~~

@lhdev ~~If the video shows what you are talking about, then you should set `max-chunk-section-index` to a higher number. See https://paper.readthedocs.io/en/stable/server/configuration.html for info about the config values. I also recommend useing `chunk-edge-mode: 2`~~

@egg82 Thanks for giving it a try.

**Comment by tsiedsma** [comment]
@stonar96 it's not the same thing as in that video, I'll figure out how to make one and post it.
I tried chunk-edge-mode: 2 and that didn't help.  It's like a render distance thing, as soon as you travel far enough away that you start rendering different chunks, those chunks render with the ores visible.  If (using EssentialsX) /spawn and then /back, the ores are gone.

**Comment by tsiedsma** [comment]
Ok, the video sucks but it shows what I'm seeing.
https://www.youtube.com/watch?v=LrkhpLxUWEM

You should see that the initial area around me has no ores at the lower Y levels.
As I travel, you can see them in the distance.  Once I /back and /back, you see the ores are gone until I travel again.

Current Config after trying different settings:
```
    anti-xray:
      enabled: true
      engine-mode: 1
      chunk-edge-mode: 1
      max-chunk-section-index: 2
      update-radius: 4
```
