### ISSUE TITLE
Auto-replenish chests

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1579]
### What behaviour is expected:
I have tried setting the auto-replenish to true in order to get the ships to replenish.
```
    lootables:
      auto-replenish: true
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
```

### What behaviour is observed:
I  do not see any replenish behaviour. Does it work? Did I made a mistake in setting it up?

### Steps/models to reproduce:
Clean world.
Players start to discover ships.
Takes the stuff.
Leaves the chest on its place.
Other player discovers the ship.
Chest remains empty

### Plugin list:
(imho not important in this case)

### Paper build number:
very latest (368), but this behaviour is seen for a while
