### ISSUE TITLE
Inconsistent Mob behavior

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1683]
### What behaviour is expected:
We've noticed some strange mob spawn-despawn behavior which we want to address.
There are several parameters that are involved here. For this test I rise around 128 block above ground level, at night.

Test 1 with the default settings:
spigot.yml
```
view-distance: 10
mob-spawn-range: 8
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
      water: 16
      tick-inactive-villagers: true
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
```
paper.yml
```
    despawn-ranges:
      soft: 32
      hard: 128
```
This allows mobs to spawn within a radius of 8 chunks, outside of this despawn immediately. What is curious is that mobs are triggered and move to just underneath the player as if they are triggered.

Test 2 with edited settings as some websites advice as optimized
spigot.yml
```
view-distance: 10
mob-spawn-range: 3
    entity-activation-range:
      animals: 8
      monsters: 12
      misc: 4
      water: 16
      tick-inactive-villagers: false
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
```

paper.yml
```
    despawn-ranges:
      soft: 28
      hard: 96
```

This should allow mobs to spawn within a radius of 3 chunks, outside of 96 despawn immediately. What is curious is that mobs are still triggered and move to just underneath the player as if they are triggered.

### What behaviour is observed:
With test 1 you see mobs:
Good: spawn with a radius of < 128 
Good: despawn right away if you move higher above ground >128
Strange: they got triggered so they see the player although distance > 32 blocks away.

With test 2 you see mobs:
Strange: spawn between a radius of 96 < 128 and rapidly despawn. Live time ~ 0.2 sec. This looks similar to the flickering mob issue in 1.13.
Strange: mobs spawn although > 3 chunks away (`mob-spawn-range: 3`)
Good: mobs don't spawn if > 128 blocks away
Strange: they got triggered so they see the player although > 32 blocks away.

Conclusion: it not recommended to alter these default settings because:
mob-spawn-range is ignored
entity-activation-range is ignored
hard despawn-range causes mobs to flicker (spawn/despawn)

### Plugin list:
not important

### Paper build number:
447, but it's not very important

I hope someone can investigates and maybe even confirm my findings.
