### ISSUE TITLE
Squids spawning

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#1692]
### What behaviour is observed:
In my world we've noticed a bit low squid numbers.

Bukkit.yml
```
spawn-limits:
  monsters: 75
  animals: 15
  water-animals: 15
  ambient: 3
```
I have the feeling that players with guardian farms eat up all the resources for spawning water animals. So if a few players are near their sea farms, other fish like animals don't spawn easy naturally anymore. I could use a mob limiter to kill guardians, but I don't think that is the solution. Raising the water-animals would probably increase the number of guardians, rather than divide the number of mobs between the online players.

### Steps/models to reproduce:
not easy to test

### Paper build number:
git-Paper-447 (MC: 1.13.2)
