### ISSUE TITLE
Alternative item-despawn-rate

### ISSUE THREAD

**Issue by CeIebrimbor** [PaperMC/Paper#1710]
**Is your feature request related to a problem? Please describe.**
No, just another improvement over Spigot. And yet another way Paper eliminates the need for crap like ClearLag.

**Describe the solution you'd like**
Option (default=disabled) to set certain ground entities to a custom despawn rate that is faster (or slower) than Spigot's item-despawn-rate. All other items not whitelisted will use Spigot's item-despawn-rate.

Paper does this with arrow despawning, so it seems like common sense to open it up to item despawn rates. 😃 

For example...
```
alt-item-despawn-rate:
  enabled: true
  removal-time: 1200
  items:
    - COBBLESTONE
    - STONE
    - DIRT
    - SAND
    - SNOWBALL
    - NETHERRACK
```

The end user has the option to use this as a whitelist or a blacklist.
- Whitelist, as seen above.
- Blacklist, by setting high-value items (Diamonds, Nether Stars, etc) at 6000 in Paper and dropping Spigot's despawn rate for all other items.
