### ISSUE TITLE
Massive performance degradation with entity ticking.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#1791]
Paper dev 493

@electronicboy Did one of your entity commit patches recently break entity ticking? Such as possibly forever ticking spawned entities and never "forgetting" them when unloaded or outside activation ranges? I'm having massive performance degradation due to tickEntity and entityTick after updating to newer Paper builds. Performance just continues to get worse the longer the server has been up.

```
    entity-activation-range:
      animals: 16
      monsters: 24
      misc: 4
      water: 12
      tick-inactive-villagers: true
```

https://timings.aikar.co/?id=55612766e3ba430cbb0e24ac32ade4d0

Edit: Or perhaps something upstream in spigot broke? :(
https://timings.aikar.co/?id=d64f3f81a4a84ae3b4e524281d571e46
https://timings.aikar.co/?id=48466c5bc10344c4acfe6aa7b3f8444f
https://timings.aikar.co/?id=27fafa4f87094ede9ec907eb4d895f6e
