### ISSUE TITLE
Frosted Ice won't melt

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#1946]
Frosted Ice no longer melts, but remains in its last status. 
I didn't change anything, at least a thought so. 
I appreciate any help you can provide :)
For testing purposes I also took down all plugins, but the problem still occurs. I don't quite know if I should change the delays? In the description in the paper documentation ("Sets the minimum delay for potion effects on frosted ice") I don't quite understand what is meant by "potion effects" :/ 

Paper.yml:
```
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
```
Paper 1.13.2 - 608
