### ISSUE TITLE
custom no permission message, can't find messages.no-permission option in paper.yml

### ISSUE THREAD

**Issue by leifadev** [PaperMC/Paper#2217]
I opened an issue about having a custom no permission message, and electronicboy responded:
> messages.no-permission (in paper.yml) 
> 
With the other suggestion that I can use plugins to override the message. I was confused on to what he meant by this. Is there a way I can add this into my paper.yml, I couldn't find `messages.no-permission` anywhere. Do I add this somehow in the `messages:` section of the paper.yml? Thanks so many guys! (Sorry for being annoying if I am) Also, was this whole thing a reference to coding something in Java that I didn't get?

**Comment by ShaneBeee** [comment]
its around line 49
```yaml
messages:
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error.'
```
