### ISSUE TITLE
Mob spawn capping patch breaks chunk based special spawns.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#235]
Tested as of Paper commit https://github.com/PaperMC/Paper/commit/3591fb7ed930e20d7cde342719b38fe637921adf

https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0139-Allow-capping-number-of-attempts-at-spawning-mobs.patch

This patch seems to affect special chunk based mob spawns. For example, guardians spawning at water temples, slime chunks, iron golem farms, etc. Eventually mobs stop spawning altogether in those special chunks. Even with using Essential's global butchering command to remove all aggressive mobs in all loaded chunks, no mobs spawn.

Usually when I butcher all 'monsters' globally with `/ebutcher monsters all world`, a bunch of guardians spawn in bulk at the temple farm. Presumably due to the global spawn limits. 

However with the patch, no matter what I do, guardians eventually don't respawn at all. I have tried teleporting away and back, teleporting someone else in the area, and of course removing all mobs in all loaded chunks. Moving to a different temple, guardians are able to spawn. Raising the cap limit is not a fix, as eventually it'll hit that cap and stop spawning again.

Removing the patch, the guardian farm I have tested at seems to be fine after many butchers and a long duration of time (with guardians auto killing themselves in lava). No matter how much time passes and how many 'global butchers' are ran, guardians are always able to continuously spawn at the temple area.

Bukkit.yml - Relevant chunk/mob based settings.

```
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 0
```

Spigot.yml - Relevant chunk/mob based settings.

```
    mob-spawn-range: 4
    nerf-spawner-mobs: false
    entity-activation-range:
      animals: 16
      monsters: 24
      misc: 4
    entity-tracking-range:
      players: 160
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    max-entity-collisions: 4
    view-distance: 6

```

Paper.yml - Relevant chunk/mob based settings.

```
    use-chunk-inhabited-timer: true
    spawner-nerfed-mobs-should-jump: false
    mob-spawner-tick-rate: 20
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    despawn-ranges:
      soft: 32
      hard: 128
    all-chunks-are-slime-chunks: false
    queue-light-updates: true
    max-mob-spawn-attempts: 50
```
