### ISSUE TITLE
Optimize minecraft::world - tracker.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#249]
Are there any optimizations that can be done to the minecraft tracker? It seems to be the biggest cause for performance issues on my server.

https://timings.aikar.co/v2/?id=81e719383cfb4a1dab098d4c56b9452c&section=lag
https://timings.aikar.co/v2/?id=f47a4e2f7eb74febad55e4dc6c2304fe&section=lag
https://timings.aikar.co/v2/?id=72a60d7cbd8d4aeebe9729e1b689ff68&section=lag

Assuming this setting is related, this is what I use.

```
    entity-tracking-range:
      players: 160
      animals: 48
      monsters: 48
      misc: 32
      other: 64
```

```
    entity-activation-range:
      animals: 16
      monsters: 24
      misc: 4
```

I use a high player range so players can see each other in the distance.

Custom compiled Paper as of this commit https://github.com/PaperMC/Paper/commit/ef64712c6cd43007574bb42e71493649c743dc3b without this patch https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0139-Allow-capping-number-of-attempts-at-spawning-mobs.patch due to all the issues it causes.
