### ISSUE TITLE
Alternative mobs-despawn-rate

### ISSUE THREAD

**Issue by Ghost-chu** [PaperMC/Paper#2496]
**Is your feature request related to a problem? Please describe.**
My player build the mob farm, so many mobs on my sevrer and won't despawn.
**Describe the solution you'd like**
Option (default=disabled) to allow set custom max live time for special mob type with named or tamed.
**Describe alternatives you've considered**
```
enabled: true
default-max-live-time: 1200
mode: 0
  mobs:
    ZOMBIE:
      max-live-time: 1200
      include-named: false
      include-tamed: false
    ENDERMAN:
      max-live-time: 1200
      include-named: true
      include-tamed: false
    PIGZOMBIE:
      max-live-time: 1200
      include-named: false
      include-tamed: false
```
**Additional context**

- whitelist see above
- blacklist see above
