### ISSUE TITLE
Activated animals outside activation range

### ISSUE THREAD

**Issue by x1p** [PaperMC/Paper#2685]
### What behaviour is expected:
I would expect all animals outside the activation range to be less active

### What behaviour is observed:
Baby animals, sheared (adult) sheeps and turtles are extremely active even far beyond the activation range.

### Steps/models to reproduce:
Place different animals in different state in a fenced area
Walk to a point (far) outside the activation range (spigot.yml)

### Plugin list:
irrelevant

### Paper build number:
Paper-1.14.4 build 225

### Anything else:
Spigots settings for this test:
```
    entity-activation-range:
      raiders: 48
      animals: 8
      monsters: 24
      misc: 8
      water: 8
      tick-inactive-villagers: false
```
