### ISSUE TITLE
Auto-replenish chests

### ISSUE THREAD

**Issue by dwesolowski** [PaperMC/Paper#2711]
### What behavior is expected:
I have tried setting the auto-replenish to true in order to get chests to replenish. I expected within the set time that the contents would refill with the new loot table items not just add them in with the last contents.

```
lootables:
   auto-replenish: true
   restrict-player-reloot: true
   reset-seed-on-fill: true
   max-refills: -1
   refresh-min: 1m
   refresh-max: 3m
```

### What behavior is observed:
Chests seem to replenish within the given time by adding more items but does not clear the chest contents first so more and more items keep adding on every replenish.

### Steps to reproduce:
Clean world
Discover chest
View contents
Wait
Recheck contents
Chest items increasing

### Plugin list:
Don't apply here

### Paper build number:
Latest build 230

### Anything else:
Would be great to clear the chest contents, then add the items from the new seed.
