### ISSUE TITLE
Auto-replenish chests reloot

### ISSUE THREAD

**Issue by dwesolowski** [PaperMC/Paper#2715]
### What behavior is expected:
Returning to a chest that I looted I can loot it again after it replenishes.

```
lootables:
   auto-replenish: true
   restrict-player-reloot: true
   reset-seed-on-fill: true
   max-refills: -1
   refresh-min: 1m
   refresh-max: 3m
```

### What behavior is observed:
Chests to remain empty until another player opens it then you can return and loot it again.

### Steps to reproduce:
Clean world
Discover chest
View contents
Loot
Wait
Recheck contents
Loot again.

### Plugin list:
Don't apply here

### Paper build number:
Latest build 230
