### ISSUE TITLE
1.15 Waterfall incompatibility 

### ISSUE THREAD

**Issue by Fernthedev** [PaperMC/Paper#2738]
### What behaviour is expected:
___The result is connecting to the server sucessfully___

### What behaviour is observed:
___The server is treated as if it's outdated as seen here___

![image](https://user-images.githubusercontent.com/15272073/70837052-aa911e00-1dd8-11ea-8aea-a9d6fdc60e5a.png)

### Steps/models to reproduce:
___Same configuration as any server. The only change was the jar and the world___
```yaml
  newsurvival:
    motd: "&1Just another Waterfall - Forced Host"
    address: localhost:25569
    restricted: false
```

### Plugin list:
___A list of your plugins___
AdvancedBan*, BungeeTabListPlus*, Chairs, Citizens, CoreProtect, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FernCommands, LuckPerms, NametagEdit*, OldCombatMechanics, ProtocolLib, SpectatorToggle, Vault, ViaVersion*, WorldBorder, WorldEdit

### Paper build number:
___git-Paper-4 (MC: 1.15)___

### Anything else:
___Some string or check done in Paper is causing it to believe the client is outdated while on Minecraft 1.15___
