### ISSUE TITLE
Crash in CraftLootableInventoryData

### ISSUE THREAD

**Issue by alekso56** [PaperMC/Paper#290]
# Crash, Stacktrace
### Link/paste of stack trace

[http://pastebin.com/raw/vy1PP97R](http://pastebin.com/raw/vy1PP97R)
### Plugin list:

 CleanroomGenerator, Questioner, ViaVersion, Backpacks, Skript, OpenInv, PluginManagerReloaded, WorldBorder, Bookcase, FastAsyncWorldEdit, AlwaysOnline, PermissionsEx, CraftingPlus, Vault, MassiveCore, UltraCosmetics, PerWorldInventory, CreativeGates, LWC, ASkyBlock, WorldEdit, Essentials, Jobs, Citizens, Vampire, LogBlock, PlotSquared, WorldGuard, EssentialsGeoIP, EssentialsSpawn, Denizen, Multiverse-Core, CraftBook, Towny, CS-CoreLib, Sentry, Slimefun, SensibleToolbox
### Actions to reproduce (if known):

I assume this is from paper.yml:

```
lootables:
      auto-replenish: true
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d

```
### Paper build number:

Paper version git-Paper-727 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
