### ISSUE TITLE
use-hopper-check breaks vanilla hopper behavior.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#299]
Paper dev 748

With use-hopper-check enabled, vanilla hopper behavior breaks. Hoppers lose track of items and the direction it should flow in when numerous hoppers are stacked on top of each other in various directions. (i.e. potatoes aren't being sorted at all and are put into the junk chest) As well as had 2 items tick at once rather than one at a time.

Region file for testing. Two different hopper item sorters in the area. Should sort carrots, potatoes, and junk into separate chests.

Paper config
`use-hopper-check: true`

Spigot config;

```
    ticks-per:
      hopper-transfer: 24
      hopper-check: 24
    hopper-amount: 1
```

Disabling the setting, the hopper sorter works as intended.

Paper config
`use-hopper-check: false`

Spigot config;

```
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
```
