### ISSUE TITLE
Graceful exit within Docker seems to be impossible

### ISSUE THREAD

**Issue by scrayos** [PaperMC/Paper#3062]
### What behaviour is expected:
A graceful exit of the server instance within the docker container and a log-output along the lines of the default output:
```
[14:12:53 INFO]: Stopping server
[14:12:53 INFO]: Saving players
[14:12:53 INFO]: Saving worlds
[14:12:53 INFO]: Saving chunks for level 'world'/minecraft:overworld
[14:12:54 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:12:54 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
```
Also the players should be disconnected cleanly with "Server closed" and the onDisable methods of the plugins should be invoked.

### What behaviour is observed:
A forceful exit of the server instance within the docker container and a log-output of
```
testserver   | 2020-03-23 12:08:17,939 Thread-1 WARN [AsyncContext@270421f5] Ignoring log event after log4j was shut down.
testserver   | 2020-03-23 12:08:17,939 Thread-1 WARN Ignoring log event after log4j was shut down
```
Players are not disconnected cleanly but instead display that the connection was closed and no plugins are cleanly disabled.

### Steps/models to reproduce:
* Configure a docker container with for example docker compose. My file looks like this:
```
version: '3.7'

services:
    bauserver:
        container_name: 'testserver'
        image: 'openjdk:13-oracle'
        volumes:
        - type: 'bind'
          source: '/home/scrayos/Downloads/testserver__1_15_2'
          target: '/home/minecraft'
        ports:
        - '25565:25565/tcp'
        working_dir: '/home/minecraft'
        stop_grace_period: '1m'
        stop_signal: 'SIGINT'
        command: ['java', '-jar', 'server.jar']
```
* Start said server with `docker-compose up` 
* Give it time to fully start up
* Stop the server either by pressing CRTL-C (SIGINT) or sending SIGINT by `docker exec testserver kill -s SIGINT 1`

### Plugin list:
none

### Paper build number:
This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT

### Anything else:
I've already did quite extensive testing on this matter and also did the same thing with the regular spigot.jar. While it seems to indeed work just fine on Spigot (players are disconnected cleanly, onDisable is invoked, only logging did sometimes miss the last line) I was unable to get it to work with Paper. I've tried different java versions, checked that the PID is indeed `1`, tried different ways of execution (shell vs exec form vs sh execution), used dockers init/tini approach to act as a proxy for the signals, confirmed that the correct signals reach the java container just fine with a dummy-jar and used different JDKs, but nothing seemed to work. So I guess this problem is within Paper, especially since it works just fine with newest spigot (git-Spigot-6de3d4b-796eb15).

Thanks in advance!
