### ISSUE TITLE
Lootables auto-replenish for filled chests

### ISSUE THREAD

**Issue by TheoRetisch1** [PaperMC/Paper#3178]
Currently, the loottables of chests are only replenished with the "auto-replenish: true" feature if the chests have been completely looted.
However, it turns out that players are very selective when it comes to looting. Nobody has to give away space and some also put their trash in the chests.
It would be very cool if the contents of the chest could simply be overwritten after a player has opened it for the first time.

```
    lootables:
      auto-replenish: true
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
```

**Comment by aikar** [comment]
I feel like this would be better left to a plugin, which I included events for.

This is asking to make it a destructive replenish, instead of additive.

It should be adding new items onto the existing. 
This is the case right? And you rather it just clear then add?

**Comment by TheoRetisch1** [comment]
Mhh I don't really care if the items are deleted or added, the result is the same. 
No, at the moment chests that are not completely emptied are completely ignored. Since most of the chests are affected, in reality chests are rarely refilled. For this reason I don't think it makes sense to leave this small but effective change in an otherwise very well thought-out feature  to a plugin.
I have tested this on version 1.15.2 build 185.

**Comment by Machine-Maker** [comment]
Maybe a per-world config would work here? either add stuff to the chest when replenished, replace contents with new roll of the loot table, or do nothing unless the chest is empty.

**Comment by TheoRetisch1** [comment]
The problem still exists and I would love to use the suggested feature :)

**Comment by TheoRetisch1** [comment]
The problem still exists and I would love to use the suggested feature :)

**Comment by TheoRetisch1** [comment]
I would still love to use the suggested feature :)

**Comment by e-im** [comment]
This does seem to be the current behaviour. I haven't looked if something has changed since when this issue was opened, but this is how it works now. No items are deleted, however new items are added. This holds true even if the player adds their own items to the chest, it will still be replenished. The only case where this will not happen is if the chest is completely full, in which case you will get a `Tried to over-fill a container` message printed to the log, or if the player has broken and re-placed the chest.

Reproduced with this config:
```yaml
    lootables:
      auto-replenish: true
      restrict-player-reloot: false
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 5s
      refresh-max: 10s
```
