### ISSUE TITLE
Add Ancient Debris and Nether Gold Ore to the default anti-xray hidden block list.

### ISSUE THREAD

**Issue by kittenchilly** [PaperMC/Paper#3665]
**Is your feature request related to a problem? Please describe.**
Ancient Debris and Nether Gold Ore are the new ore types that were added into the 1.16 nether update. They are not currently on the anti-xray default hidden block list, meaning many people can abuse x-ray for finding this ores on servers that forget to add it manually.

**Describe the solution you'd like**
Simply adding Ancient Debris and Nether Gold Ore to the default hidden block list should fix this problem.

**Comment by stonar96** [comment]
In my opinion this shouldn't be added to the default list. If you want a proper setup for Anti-Xray this should be done with per world config anyway. Adding this to the default list will result in people ignoring the fact that they should add sections per world.

Edit: See https://gist.github.com/stonar96/ba18568bd91e5afd590e8038d14e245e

**Comment by Puremin0rez** [comment]
It should be noted that anti xray won't work too well in the nether anyways right now because it requires the chunk section indexes to be configured differently to apply to the full height of the world.

Pretty sure Aikar (or someone) is going to address this.

**Comment by ghost** [comment]
```
  world_nether:
    anti-xray:
      enabled: true
      engine-mode: 1
      chunk-edge-mode: 2
      max-chunk-section-index: 7
      update-radius: 2
      hidden-blocks:
      - nether_quartz_ore
      replacement-blocks:
      - netherrack
```
