### ISSUE TITLE
All structures in all worlds (not just nether) are not generating after updating to 1.16

### ISSUE THREAD

**Issue by ryan-bing** [PaperMC/Paper#3900]
### What behaviour is expected:
Structures such as villages, woodland mansions, shipwrecks, etc should generate in the overworld.

### What behaviour is observed:
After updating to 1.16, newly generated chunks do not contain any structures, even when they should be there according to the /locate command. 

https://imgur.com/a/A6qLFuV

### Steps/models to reproduce:
All I did was update to 1.16.

### Plugin list:
Chair, ChestTerminal, Citizens, CS-CoreLib, dTools, DyedBackpacks, EffectLib, Essentials, EssentialsChat, EssentialsSpawn, ExoticGarden, ExtraGear, ExtraHeads, GriefPrevention, HolographicDisplays, IllegalStack, LogBlock, LuckPerms, mcMMO, MegaSlime, MobFarmManager, Multiverse-Core, NBTAPI, NerfPhantoms, PlayerShopGUIPlus, PlugMan, ProtocolLib, Sentinel, ShopGUIPlus, Slimefun, SlimefunLuckyBlocks, spark, VarLight, Vault, WorldEdit, WorldGuard

### Paper build number:
Paper-90

### Anything else:
I know #3720 posted something similar, but the steps to fix the problem did not work for me; in our level.dat it has generate structures set to 1 for all worlds (overworld, nether, end, and spawn world). This is also not limited to just the overworld, but to all worlds on the server. Chunks generated prior to 1.16 have their structures, but no new chunk have structures.

**Comment by ryan-bing** [comment]
Here are some updates:

I updated to 1.16 on June 29, and unloaded a bunch of unused worlds on July 5. I just went through these worlds and realized that one of them had generate_features set to 0:

![](https://i.imgur.com/Ousa4Cz.png)

However, I know for certain that this is NOT the main world, nor has it ever been set to be the main world. Furthermore, after it was unloaded and removed from the Multiverse config, my world still does not generate structures. Today, we removed the world folder from the directory and restarted -- structures still do not generate.

We only have four worlds loaded (3 main worlds + spawn world), and all of them have generate_features set to 1:

The overworld:
![](https://i.imgur.com/lRxAUAQ.png)

The nether:
![](https://i.imgur.com/1RI99cz.png)

The end:
![](https://i.imgur.com/TVKZArN.png)

Spawn world:
![](https://i.imgur.com/8Yk0FY2.png)

There are other worlds in the server directory that are NOT loaded in. Regardless, we checked all of these and generate_features is set to 1. The only world that this is not the case is a test world that's been unloaded since July 2019 and doesn't even have generate_features:

![](https://i.gyazo.com/87c3c061e39d952d57bf7d0c41a07fa3.png)


I've verified that the main world is set to something appropriate in server.properties and in Multiverse:

server.properties:

`level-name=Main2019
`

Multiverse config:

```
multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'false'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: Main2019
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'
  autopurge: 'true'
```

Does anyone have any ideas for a quick fix while waiting for paper/spigot/multiverse to patch this?
