### ISSUE TITLE
World container setting does not work

### ISSUE THREAD

**Issue by janLindner** [PaperMC/Paper#3972]
### What behaviour is expected:
When configuring a world container in the bukkit.yml the folder should be used as a container for all worlds.

### What behaviour is observed:
When starting the server all worlds are still created in the main directory and not within the configured world container. 

### Steps/models to reproduce:
Configure `world-container: worlds` within the bukkit.yml
```yml
settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
  world-container: worlds
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 15
  water-ambient: 20
  ambient: 15
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  ambient-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml
```
Have no worlds and start the server. 

### Plugin list:
Arceon, ProtocolLib, FastAsyncWorldEdit, Dynmap

### Paper build number:
git-paper-101

### Anything else:
The API Method `Bukkit.getServer().getWorldContainer()` does also return the wrong folder. 
This might not be a bug introduced by paper but with spigot / bukkit itself.
