### ISSUE TITLE
Feature: Disable Ticking Specific TileEntities

### ISSUE THREAD

**Issue by CJCrafter** [PaperMC/Paper#4071]
**Is your feature request related to a problem? Please describe.**
Sometimes, servers have lobby worlds where builders may use hoppers, furnaces, beehives, or other tile entities as decoration. These tile entities do not serve as their original purpose (collecting items, smelting things, storing bees, etc), but are ticked anyway. For many servers, this can put strain that can easily be avoided

**Describe the solution you'd like**
I want to completely disable ticking specified tile entities. If a server wants to disable beehives in the `lobby` world, the option may look like:
```yaml
world-settings:
  lobby:
    tile-entities:
      no-tick:
        - BEEHIVE
```

**Describe alternatives you've considered**
This could also be used to specify the tick rate of each one, which may be useful to some servers who suffer from lag from these tile entities but don't want to completely disable the given tile entity.

Alternatively instead of this "one size fits all" option, we could get individual options like how hoppers have more options, but it would be more time consuming to implement and we wouldn't get all the tile entities (Too much to implement). Example: 
```yaml
world-settings:
  default:
    furnace:
      tick-rate: 1 # How often to tick the furnace
      item-amount: 1 # How many items are smelted 
```

**Additional context**
I am no expert on tile entities, I haven't a clue how safe it would be to just stop ticking a tile entity.
