### ISSUE TITLE
command-line history

### ISSUE THREAD

**Issue by cromatikap** [PaperMC/Paper#4125]
Hi,

Is there any way to add a command-line history in the console? That's to say to be able to retrieve already typed command using the up/down arrow keys.

**Comment by BillyGalbreath** [comment]
That's already a thing

**Comment by cromatikap** [comment]
What do you mean?

**Comment by BillyGalbreath** [comment]
> What do you mean?

![Peek 2020-08-13 04-47](https://user-images.githubusercontent.com/332527/90120407-54d29400-dd20-11ea-8677-91a3ebe82e88.gif)

I type a few commands, then used up/down to cycle the command history.

**Comment by cromatikap** [comment]
Okay, I'm running in in a docker container named `minecraft` and I access the console using `docker attach minecraft --detach-keys=ctrl-q`
When I use the arrows I get `^[[A` or `^[[B` written and it doesn't go through the history. Tab key doesn't work as well.
Any idea how I can fix this problem?

**Comment by BillyGalbreath** [comment]
> Any idea how I can fix this problem?

No idea. I've never used docker (trying to stay as far away from it as possible, tbh). But a quick google showed me [this conversation](https://github.com/jupyter/notebook/issues/2457) with a lot of info that seems helpful.

**Comment by cromatikap** [comment]
Okay thank you for the link.

Why are you trying to stay away from docker?

**Comment by BillyGalbreath** [comment]
> Why are you trying to stay away from docker?

Personal preference. I like being in control. ^_^

**Comment by Proximyst** [comment]
You've gotta start the container with TTY and interactive modes (`-it`).

**Comment by cromatikap** [comment]
docker-compose.yml
```
version: '3.7'

services:
  minecraft:
    image: felixklauke/paperspigot:1.16.1
    container_name: minecraft
    stdin_open: true
    tty: true
    restart: always
    environment:
      - SHELL=/bin/bash
    networks:
      - minecraft
    ports:
      - 25565:25565
    volumes:
      - config:/opt/minecraft/config
      - worlds:/opt/minecraft/worlds
      - plugins:/opt/minecraft/plugins
      - data:/opt/minecraft/data
      - logs:/opt/minecraft/logs

volumes:
  config: {}
  worlds: {}
  plugins: {}
  data: {}
  logs: {}

networks:
  minecraft: {}
```

I do `docker-compose up -d` then `docker attach minecraft --detach-keys=ctrl-q`.
I added `SHELL=/bin/bash` env var but I still face the same problem
