### ISSUE TITLE
No longer possible to enable timings from console?

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#433]
Paper dev 876.

```
timings:
  enabled: false
  verbose: false
  server-name-privacy: true
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
```

I keep timings disabled by default and enable it from console when I'd like to measure performance for a bit.

`/timings on` > `/timings paste`

Typing 'timings on' outputs;

```
[12:29:54] [Server thread/INFO]: Enabled Timings & Reset
[12:29:54] [Server thread/INFO]: Timings Reset
```

But when typing 'timings paste' after a bit of time, it outputs;

```
[12:30:06] [Server thread/INFO]: Please enable timings by typing /timings on
```

Use to work as intended. Probably broke around a month ago when timing changes were made?
