### ISSUE TITLE
Disconnecting does bad things

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#481]
Moved

**Comment by Zbob750** [comment]
The last time we got one of these, the items were client-side. Regardless, you'll have to test this against 1.11 once it's out, it's unlikely this will be looked into for 1.10.

**Comment by sudofox** [comment]
@bonces sounds like a race condition of some sort. 

>  latest nocheatplus

do you have anything nonstandard in your NCP config?

>  no other inventory modifying plugins

It could be a side effect of one of your other plugins creating a race condition that affects timing. Can you list the plugins that you use?

I would suggest seeing if it continues when Paper 1.11 is released, as @Zbob750 commented above.

**Comment by Chnkr** [comment]
Unable to replicate on vanilla.

**Comment by starcraft66** [comment]
no comment

**Comment by fr1kin** [comment]
i heard some guy named tdude66 wrote a plugin to  fix this

**Comment by KurtisAD** [comment]
Can confirm tdude66 plugin

**Comment by BillyGalbreath** [comment]
Who is tdude66, and where can we find this plugin?

**Comment by jared2013** [comment]
You can now dupe 27 stacks at once with a modded client.

**Comment by jared2013** [comment]
![2012-04-17_22 12 59](https://cloud.githubusercontent.com/assets/23563288/20452112/9a296a7a-add0-11e6-9551-3ba2bd30a868.png)

**Comment by Zbob750** [comment]
And yet, trying to provide any useful information on what causes the issue, a consistent reproduction method, or this fabled fix plugin, is now going on ten hours.

**Comment by jared2013** [comment]
It's not the largest issue at the moment. This is a contained issue that is currently affecting only a single minecraft server.

**Comment by Zbob750** [comment]
So we're not even sure its related to Paper then... alrighty.

**Comment by babbaj** [comment]
Couldn't reproduce

**Comment by jared2013** [comment]
Clearly a duplication glitch of this magnitude would present itself on more than just a single server?  Honestly, patching Paper to aid one server is quite pointless and unproductive to the project as a whole. I say leave this to the server admin. 


Also, the image from above was not created using a vanilla client @babbaj

**Comment by Tum0r** [comment]
I attempted this several times following the process stated by the OP, and I was unable to reproduce the reported bug.  If this is not possible via vanilla clients, then this issue should be pushed to the NCP team.

**Comment by 2b2tmemer** [comment]
I have been able to reproduce this bug in conditions with low TPS. The lower the TPS the more successful the exploit. For the record the above users. Tum0r, Jared, and babbaj are all long time players on the server in question and will likely actively work to make sure this bug is not resolved for personal reasons. 

This bug is an edge case but it is an issue and it is reproducible.

**Comment by jared2013** [comment]
DELETE THIS

**Comment by sudofox** [comment]
I tried several things to reproduce the issue and was ultimately unable to do so.

I tried doing it manually, and then wrote a quick custom mod into my custom client to try to do it programatically:

https://www.youtube.com/watch?v=elg5LOBwtHE&feature=youtu.be

I matched bonces versions: latest NCP and latest Paper - the build artifacts from the Jenkins, as shown in the video.
```
This server is running Paper version git-Paper-916 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

 ---- Version information ----
 #### Server ####
git-Paper-916 ~MC: 1.10.2~
detected: 1.10.2
#### NoCheatPlus ####
 Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1030
 MCAccess: 1.10 / Spigot-CB-1.10_R1
 Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
```
