### ISSUE TITLE
Players invisible after teleporting

### ISSUE THREAD

**Issue by hensih** [PaperMC/Paper#4854]
### What behaviour is expected:
Other players are visible after you /tpa to them or they /tpa to you.

### What behaviour is observed:
Players remain invisible after teleporting to them.

### Steps/models to reproduce:
antixray turned on, with engine-mode: 2

### Plugin list:
ActionBarAPI, AdvancedEnchantments, AuctionGUIPlus, AuthMe, AutoBroadcast, Autorank, BeastWithdraw, BetterFarming, BetterRTP, BetterSleeping3, BloodInMinecraft, Chair, ChatGames, ChestShop, ChestSort, ChristmasCalendar, Chunky, Citizens, ColoredAnvils, CommandPanels, CoreProtect, CrateReloaded, CustomJoinMessages, DailyRewards, DeluxeMentions, Denizen, DurabilityAlert, dynmap, eGlow, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FreeRPG, GameBox, HackedClientDetect, HolographicDisplays, InteractiveChat, Jobs, LibsDisguises, LuckPerms, LWC, MineableSpawners, MobArena, Multiverse-Core, Multiverse-Portals, MythicMobs, Negativity, PetBlocks, PlaceholderAPI, PlayerListDeluxe, PlayerShopGUIPlus, ProtocolLib, SalaryManager, ServerlistMOTD, ShopGUIPlus, SimpleHealthbars2, SkinsRestorer, Statz, TempFly, TitleManager, TreasureHunt, Vault, ViaVersion, Votifier, VotingPlugin, VoxelSniper, WildChests, WildStacker, WorldEdit, WorldGuard

### Paper version:
paper-1.16.4-312
Running minecraft 1.16.4

### Anything else:
Previous installation was latest Spigot 1.16.3

```
    anti-xray:
      enabled: true
      engine-mode: 2
      max-chunk-section-index: 3
      update-radius: 2
      lava-obscures: false
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      - air
      - spawner
      replacement-blocks:
      - stone
      - oak_planks
    viewdistances:
      no-tick-view-distance: -1
    squid-spawn-height:
      maximum: 0.0
    generator-settings:
      flat-bedrock: false
  earth_nether:
    anti-xray:
      max-chunk-section-index: 7
      hidden-blocks:
      - air
      - ancient_debris
      - bone_block
      - glowstone
      - magma_block
      - nether_bricks
      - nether_gold_ore
      - nether_quartz_ore
      - polished_blackstone_bricks
      replacement-blocks:
      - basalt
      - blackstone
      - gravel
      - netherrack
      - soul_sand
      - soul_soil
  earth_the_end:
    anti-xray:
      enabled: false
```
