### ISSUE TITLE
Empty lines in itemmeta are removed

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#4978]
### What behaviour is expected:
Normal itemstacks that behave normally 

### What behaviour is observed:
Serialized itemstacks look like this and are missing empty lines
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: STONE_HOE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Test Item"}],"text":""}'
      lore:
      - '{"extra":[{"text":"It''s not that delightful."}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Line 1"}],"text":""}'
      - ''
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Line 2"}],"text":""}'
      - ''
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Line 3"}],"text":""}'
      enchants:
        MENDING: 1
        DAMAGE_ALL: 10
        DURABILITY: 10

### Paper version:
1.16.4 364

**Comment by Proximyst** [comment]
Am I missing something?

```yaml
debug-item:
  ==: org.bukkit.inventory.ItemStack
  v: 2584
  type: WRITTEN_BOOK
  meta:
    ==: ItemMeta
    meta-type: BOOK_SIGNED
    lore:
    - '{"extra":[{"text":"abc"}],"text":""}'
    - '{"text":""}'
    - '{"extra":[{"text":"cool"}],"text":""}'
    enchants:
      ARROW_DAMAGE: 3
    pages:
    - '{"extra":[{"text":"Testing book"}],"text":""}'
```

```kotlin
class SaveItemConfigCommand : BaseCommand() {
    override fun register(manager: PaperCommandManager<CommandSender>) {
        manager.command(manager.commandBuilder("saveitemconfig")
            .handler {
                DebugPlugin.instance.config["debug-item"] = ItemStack(Material.WRITTEN_BOOK).modifyMetaAs<BookMeta> {
                    addPage("Testing book")
                    addEnchant(Enchantment.ARROW_DAMAGE, 3, true)
                    lore = listOf(
                        "abc",
                        "",
                        "cool"
                    )
                }
                DebugPlugin.instance.saveConfig()
            })
    }
}
```
