### ISSUE TITLE
Loot chests can be re-looted by player.

### ISSUE THREAD

**Issue by dwesolowski** [PaperMC/Paper#5131]
I am assuming the  restrict-player-reloot: true setting should prevent returning and re-looting?

### What behavior is expected:
- Loot all items in chest
- Wait the refill time
- Chest refilled
- Should not be able to reloot by same player

### What behavior is observed:
- Loot all items in chest
- Wait the refill time
- Chest refilled
- Loot all items again by same player
- Also wanted to note that I don't see consistent timings monitoring the LootableInventoryReplenishEvent event vs the set config values for refresh min max.

### Steps to reproduce:
- /give @p minecraft:chest{BlockEntityTag:{LootTable:"minecraft:chests/spawn_bonus_chest"}}
- Loot all items in chest
- Wait the refill time
- Chest refilled
- Loot all items again by same player

### Plugin list:
None

### Paper version:
Paper ver 1.16.5 build 449

```
Current settings.
    lootables:
      auto-replenish: true
      max-refills: -1
      refresh-max: 2m
      refresh-min: 1m
      reset-seed-on-fill: true
      restrict-player-reloot: true
```
