### ISSUE TITLE
Lava flows too fast in overworld

### ISSUE THREAD

**Issue by zedwick** [PaperMC/Paper#521]
# Incompatibility (Bug)

### What behaviour is expected:
Lava should flow at normal (fairly slow) speed in the overworld
### What behaviour is observed:
Lava flows fast (Same speed as water?) in the overworld
### Steps/models to reproduce:
Get a bucket of lava, pour onto ground.
Compare the flow rate with single player if needed.

### Paper.yml

```
fast-drain:
      lava: false
      water: false
    lava-flow-speed:
      normal: 30
      nether: 10
```

### Spigot?
This behaviour does not occur in spigot.

### Plugin list:
0 plugins

### Paper build number:
This server is running Paper version git-Paper-944 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
