### ISSUE TITLE
Option to disable firework player damage.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#569]
Would it be possible to implement a Paper setting to disable player damage when in the vicinity of a firework going off? Quite a few plugins use fireworks for effects, resulting in players getting hurt now in 1.11+.

E.g.
McMMO leveling up / using abilities.

**Comment by MiniDigger** [comment]
the plugins that use fireworks should handle that themselves

**Comment by sgdc3** [comment]
+1 for this, it's a gameplay feature that should be configurable.

**Comment by zachbr** [comment]
... isn't this one of those things easily done in a tiny plugin?

**Comment by sgdc3** [comment]
Nope, the only way to disable the damage is very ugly:

```Java
package it.feargames.safefireworks;

import org.bukkit.entity.Entity;
import org.bukkit.entity.Firework;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.event.entity.FireworkExplodeEvent;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitRunnable;

import java.util.HashSet;
import java.util.Set;

public final class SafeFireworks extends JavaPlugin implements Listener {

    private Set<Firework> fireworks;

    @Override
    public void onEnable() {
        fireworks = new HashSet<>();
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler(ignoreCancelled = true)
    public void onExplosion(FireworkExplodeEvent event) {
        final Firework firework = event.getEntity();
        fireworks.add(firework);
        new BukkitRunnable() {
            @Override
            public void run() {
                fireworks.remove(firework);
            }
        }.runTaskLater(this, 5);
    }

    @EventHandler(ignoreCancelled = true)
    public void onDamage(EntityDamageEvent event) {
        for(Entity entity : event.getEntity().getNearbyEntities(5, 5, 5)) {
            if(!(entity instanceof Firework)) {
                continue;
            }
            if(fireworks.contains(entity)) {
                event.setCancelled(true);
                return;
            }
        }
    }
}
```

**Comment by zachbr** [comment]
Looks like there is currently a bug in the API that prevents someone from listening to EntityDamageByEntityEvent and easily cancelling it there.

That issue will be resolved, there will not be a configuration option added.

**Comment by sgdc3** [comment]
I still think it would make more sense to add an option, look at the other existing game mechanics related paper.yml entries.

**Comment by zachbr** [comment]
This is now working as of builds 1021+
```java
@EventHandler
public void onEntityDamageByEntity(EntityDamageByEntityEvent event) {
    if (event.getDamager() instanceof Firework && event.getEntity() instanceof Player) {
        event.setCancelled(true);
    }
}
```

**Comment by sgdc3** [comment]
Oh thanks.... now spigotmc.org will be filled with 100 identical "plugins"

**Comment by zachbr** [comment]
Feel free to fork and do it yourself rather than just complaining. Or hell, copy and paste what I just wrote.
Why don't we add configuration options for everything else while we're here. I really hate how creepers blow up, I know a plugin could do it with less work and less maintenance burden but I really think we should bury it in a config.

Please.

**Comment by sgdc3** [comment]
> Feel free to fork and do it yourself rather than just complaining.

What's the sense if you'll close the PR?

> Or hell, copy and paste what I just wrote.

It was the fist version of code I tried to use.
Thank you for fixing the EntityDamageByEntityEvent, but i still think it should be a built-in feature.

> I really hate how creepers blow up, I know a plugin could do it with less work and less maintenance burden but I really think we should bury it in a config.

"Paper is a high performance fork of the Spigot Minecraft Server that aims to **fix gameplay and mechanics inconsistencies** and improve performance."

**Comment by sgdc3** [comment]
```
# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our IRC channel.
# 
# IRC: #paper @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=paper )
# Wiki: https://paper.readthedocs.org/ 
# Paper Forums: https://aquifermc.org/ 

config-version: 12
settings:
  player-auto-save-rate: -1
```
  **enable-player-collisions: true**
```
  bungee-online-mode: true
  load-permissions-yml-before-plugins: true
  save-empty-scoreboard-teams: false
  remove-invalid-statistics: false
  region-file-cache-size: 256
  incoming-packet-spam-threshold: 300
  sleep-between-chunk-saves: false
  min-chunk-load-threads: 2
  set-health-before-death-event: false
timings:
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
messages:
  kick:
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
world-settings:
  default:
    verbose: false
    keep-spawn-loaded-range: 8
    auto-save-interval: -1
    allow-non-player-entities-on-scoreboards: false
    hopper:
      push-based: false
```
    **nether-ceiling-void-damage: false**
    **enable-treasure-maps: true**
    **treasure-maps-return-already-discovered: false**
```
    game-mechanics:
      disable-end-credits: false
      disable-chest-cat-detection: false
    container-update-tick-rate: 1
    remove-corrupt-tile-entities: false
    lava-flow-speed:
      normal: 30
      nether: 10
    use-chunk-inhabited-timer: true
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    despawn-ranges:
      soft: 32
      hard: 128
    max-growth-height:
      cactus: 3
      reeds: 3
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    fast-drain:
      lava: false
      water: false
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      flat-bedrock: false
    non-player-arrow-despawn-rate: -1
    disable-explosion-knockback: false
    elytra-hit-wall-damage: true
    enable-old-tnt-cannon-behaviors: false
    use-alternate-fallingblock-onGround-detection: false
    grass-spread-tick-rate: 1
    portal-search-radius: 128
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    max-auto-save-chunks-per-tick: 24
    delay-chunk-unloads-by: 10s
    queue-light-updates: false
    use-vanilla-world-scoreboard-name-coloring: false
    optimize-explosions: false
    save-queue-limit-for-auto-save: 50
    water-over-lava-flow-speed: 5
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    filter-nbt-data-from-spawn-eggs-and-related: true
    keep-spawn-loaded: true
    armor-stands-do-collision-entity-lookups: true
    skeleton-horse-thunder-spawn-chance: 0.01
    disable-ice-and-snow: false
```
    **fire-physics-event-for-redstone: false**
```
    baby-zombie-movement-speed: 0.5
    spawner-nerfed-mobs-should-jump: false
    allow-leashing-undead-horse: false
    all-chunks-are-slime-chunks: false
    mob-spawner-tick-rate: 1
```
    **disable-thunder: false**
```
    disable-teleportation-suffocation-check: false

```

All features that can be implemented by a plugin "with less work and less maintenance".

P.S: Damn Markdown
