### ISSUE TITLE
 Suggestion: Make view distance per world

### ISSUE THREAD

**Issue by ArthurLaurijssen** [PaperMC/Paper#604]
Hey,
I really like how in the paper.yml you can set some settings per world. But would it be possible to change the view distance per world? I mean like in the spawn world I want it to make so players can view 5 chunks far but on the other skyblock world I want it to make it so it only loads 3 chunks to save up resources. Would this be possible?

**Comment by Gabscap** [comment]
You can set a per-world view-distance in your [spigot.yml](https://www.spigotmc.org/wiki/spigot-configuration/#per-world-settings)

Example:
```
# ...
world-settings:
  default:
    view-distance: 5
    # ...
  skyblock:
    view-distance: 3
    # ...
```
