### ISSUE TITLE
enable-brigadier-highlighting: false not works?

### ISSUE THREAD

**Issue by molor** [PaperMC/Paper#6309]
### Expected behavior

Any input must be white/gray/default console color

### Observed/Actual behavior

On Windows 10:

![image](https://user-images.githubusercontent.com/19989717/127871240-30527493-7309-4007-bd38-518ae20fa967.png)
On Windows Server 2012 R2:

![image](https://user-images.githubusercontent.com/19989717/127871174-b7ddf6f0-3dbf-4c44-8026-a74b5b9348bc.png)

### Steps/models to reproduce

```
settings:
  console:
    enable-brigadier-highlighting: false
    enable-brigadier-completions: false (maybe this can be left as true, I set it to false for tests)
```

Then try to write existing and non-existing command into console window.

### Plugin list

![image](https://user-images.githubusercontent.com/19989717/127871663-0bed5c52-f95a-46b9-b9cd-2c1e97c08275.png)

### Paper version

Happens on 1.16.5 too
```
This server is running Paper version git-Paper-151 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6e7f9aa)
You are running the latest version
```

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.
