### ISSUE TITLE
Not possible to disable advancements being displayed in chat

### ISSUE THREAD

**Issue by ghost** [PaperMC/Paper#798]
announce-player-advancements=false in server.properties
false inside level.dat
disabled in spigot.yml even if it shouldn't be the problem
```
advancements:
  disable-saving: true
  disabled:
  - minecraft:story/disabled
```

ran the gamerule from console, and
from an operator status account in the world(s)

no plugins

it still happens. could an option be added to paper to override and disable the chat announcements?

paper 1154
