### ISSUE TITLE
ItemStack overflow with amount > 127

### ISSUE THREAD

**Issue by stevmei** [PaperMC/Paper#898]
### Description of issue:
An ItemStack that is saved and loaded via FileConfiguration and has an amount > 127 cannot be restored correctly due to an internal overflow.

### Other helpful links
md5 test code on spigot with output: https://hub.spigotmc.org/jira/browse/SPIGOT-3562

### Paper build number:
This server is running Paper version git-Paper-1220 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

# Incompatibility (Bug)

### What behaviour is expected:
```
test:
  ==: org.bukkit.inventory.ItemStack
  type: STONE
  amount: 1000
test2:
  ==: org.bukkit.inventory.ItemStack
  type: WEB
  amount: 1000
```
### What behaviour is observed:
```
test:
  ==: org.bukkit.inventory.ItemStack
  type: AIR
  damage: -1
  amount: 0
test2:
  ==: org.bukkit.inventory.ItemStack
  type: WEB
```
### Steps/models to reproduce:
Running test code:
```
ItemStack i = new ItemStack( Material.STONE, 1000 );
getConfig().set( "test", i );
saveConfig();
reloadConfig();
i = getConfig().getItemStack( "test" );
getConfig().set( "test", i );
i = i.clone();
i.setType( Material.WEB );
getConfig().set( "test2", i );
saveConfig();
```

# Suggestion

Check for int to byte differences within ItemStack and also compare it to NMS.
